sudo: required
dist: trusty

branches:
  except:
    - /^v[-.0-9]+$/

language: java

jdk:
  - oraclejdk8

install: true

script: mvn -Plibrary verify && git clone https://github.com/perfectsense/travis-maven-deploy.git && travis-maven-deploy/deploy.sh
